version: '3'

services:
  app:
    container_name: local_galaveg_app
    build:
      context: ./
      dockerfile: ./deploy/local/app.Dockerfile
    links:
      - mysql
      - redis
    volumes:
      - './:/app'
    ports:
      - '${FORWARD_APP_PORT:-8080}:${APP_PORT:-8080}'
    environment:
      WWWUSER: '${WWWUSER:-1000}'
      WWWGROUP: '${WWWGROUP:-1000}'
    networks:
      - local_galaveg_network

  fake_smtp_server:
    container_name: local_galaveg_fake_smtp_server
    image: gessnerfl/fake-smtp-server:2.2.1
    hostname: "fake-smtp-server"
    restart: always
    environment:
      - FAKESMTP_AUTHENTICATION_USERNAME=${MAIL_USERNAME:-test}
      - FAKESMTP_AUTHENTICATION_PASSWORD=${MAIL_PASSWORD:-test}
    ports:
      - '${FORWARD_FAKE_SMTP_APP_PORT:-1080}:8080'
      - '${FORWARD_FAKE_SMTP_API_PORT:-1081}:8081'
      - '${FORWARD_FAKE_SMTP_PORT:-8025}:8025'
    networks:
      - local_galaveg_network

  mysql:
    container_name: local_galaveg_mysql
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_MYSQL_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'local_galaveg_mysql_volume:/var/lib/mysql'
      - './deploy/local/init.sql:/docker-entrypoint-initdb.d/init.sql'
    networks:
      - local_galaveg_network

  phpmyadmin:
    container_name: local_galaveg_phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - '${FORWARD_PHPMYADMIN_PORT:-8090}:80'
    environment:
      - PMA_ARBITRARY=1
    networks:
      - local_galaveg_network

#  valkey:
#    container_name: local_galaveg_valkey
#    image: valkey/valkey:9
#    restart: always
#    ports:
#      - '${FORWARD_REDIS_PORT:-6379}:6379'
#    volumes:
#      - 'local_galaveg_valkey_volume:/data'
#    networks:
#      - local_galaveg_network

  redis:
    container_name: local_galaveg_redis
    image: redis:latest
    restart: always
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'local_galaveg_redis_volume:/data'
    networks:
      - local_galaveg_network

volumes:
  local_galaveg_mysql_volume:
    driver: local
  local_galaveg_redis_volume:
    driver: local

networks:
  local_galaveg_network:
    driver: bridge